### PR TITLE
Made some changes that are required to be suitable for mobile version

### PR DESCRIPTION
**Pull request by ibr5500**
I added a media quire & hamburger button.
Also, added the images inside anchor tags.

### CODE REVIEW

**Review by Kingstalux — COMMENTED** [review]
Good job fixing the Webhint linters. I'll proceed with the review 👍

**Comment by ibr5500** [comment]
I have fix them now

**Comment by ibr5500** [comment]
> Good job fixing the Webhint linters. I'll proceed with the review 👍

I have fix the webhint linters could you please check it?

**Review by Kingstalux — APPROVED** [review]
Hi @ibr5500 ,
# Status: Approved  ✔️ ✔️ ✔️ 
 
68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966

Good job implementing the required changes 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
- [ ] (OPTIONAL) Even though this is optional, I strongly suggest you implement it in your next project. The width for your mobile view is too small, modern-day mobile phones do not have widths as small as what you've implemented. Kindly adjust your mobile view and it should look good at least from `380px` to `992px`
- Your site:

Annotation 2022-03-17 193618
- [ ] (OPTIONAL) Kindly remove all empty sections from your README file in order to make it more professional 👍 
- Your README file:
Annotation 2022-03-17 193348


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
